services:
    Rector\PHPUnit\Rector\ExceptionAnnotationRector: ~
    Rector\PHPUnit\Rector\GetMockRector: ~

    # ref. https://github.com/sebastianbergmann/phpunit/compare/5.7.9...6.0.0
    Rector\Rector\Namespace_\PseudoNamespaceToNamespaceRector:
        $pseudoNamespacePrefixes:
            - 'PHPUnit_'
        $excludedClasses:
            # exclude this class, since it has no namespaced replacement
            - 'PHPUnit_Framework_MockObject_MockObject'

    # handles 2nd and 3rd argument of setExpectedException
    Rector\PHPUnit\Rector\DelegateExceptionArgumentsRector: ~

    Rector\Rector\MethodCall\MethodNameReplacerRector:
        'PHPUnit\Framework\TestClass':
            'setExpectedException': 'expectedException'
            'setExpectedExceptionRegExp': 'expectedException'
