services:
    Rector\PHPUnit\Rector\SpecificMethod\AssertNotOperatorRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertComparisonToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertSameBoolNullToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertFalseStrposToContainsRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseInternalTypeToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertCompareToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertIssetToSpecificMethodRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertInstanceOfComparisonRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertPropertyExistsRector: ~
    Rector\PHPUnit\Rector\SpecificMethod\AssertRegExpRector: ~
