services:
    Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector: null

    Rector\SOLID\Rector\ClassConst\PrivatizeLocalClassConstantRector: null
    Rector\SOLID\Rector\Class_\MakeUnusedClassesWithChildrenAbstractRector: null
