services:
    Rector\Rector\Class_\ClassReplacerRector:
        $oldToNewClasses:
            'Illuminate\Http\Response': 'Symfony\Component\HttpFoundation\Response'
            'App\Http\Controllers\Controller': 'Symfony\Bundle\FrameworkBundle\Controller\Controller'


    # view('...') => $this->render('...')
    Rector\Rector\Dynamic\FunctionToMethodCallRector:
        $functionToMethodCall:
            'view': ['this', 'render']
