# .kodiak.toml
version=1

[merge]
delete_branch_on_merge=true

method="squash"

# see https://kodiakhq.com/docs/config-reference#approveauto_approve_usernames
[approve]
auto_approve_usernames="TomasVotruba"
