language: php

matrix:
  include:
    - php: 7.1
      env: STATIC_ANALYSIS=true RUN_RECTOR=true
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
      composer check-cs
      composer phpstan
    fi

  # Rector demo run
  - |
    if [[ $RUN_RECTOR == true ]]; then
      bin/rector process src --level symfony40 --dry-run
      bin/rector generate-rector-overview >> rector-overview.md
    fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
