language: php

matrix:
  include:
    - php: 7.1
      env: CODING_STANDARD=true
    - php: 7.1
      env: PHPSTAN=true
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: 7.2

install:
  - composer install

before_script:
  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - if [[ $CODING_STANDARD != "" ]]; then composer check-cs; fi
  - if [[ $PHPSTAN != "" ]]; then composer phpstan; fi

after_script:
  # upload coverage to Coveralls.io
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php coveralls.phar --verbose
    fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: never
