services:
    # https://github.com/symfony/symfony/blob/master/UPGRADE-4.1.md
    Rector\Rector\MethodCall\RenameMethodRector:
        # https://github.com/symfony/symfony/commit/463f986c28a497571967e37c1314e9911f1ef6ba
        Symfony\Component\Console\Helper\TableStyle:
            setHorizontalBorderChar: 'setHorizontalBorderChars'
            setVerticalBorderChar: 'setVerticalBorderChars'
            # special case to "getVerticalBorderChar" â†’ "getBorderChars()[3]"
            getVerticalBorderChar:
                name: 'getBorderChars'
                array_key: 3
            getHorizontalBorderChar:
                name: 'getBorderChars'
                array_key: 2

            setCrossingChar: 'setDefaultCrossingChar'

        Symfony\Component\HttpFoundation\File\UploadedFile:
            getClientSize: 'getSize'
        Symfony\Component\Workflow\DefinitionBuilder:
            reset: 'clear'
            add: 'addWorkflow'

    Rector\Rector\Class_\RenameClassRector:
        # https://github.com/symfony/symfony/commit/07dd09db59e2f2a86a291d00d978169d9059e307
        Symfony\Bundle\FrameworkBundle\DataCollector\RequestDataCollector: 'Symfony\Component\HttpKernel\DataCollector\RequestDataCollector'
        Symfony\Component\Workflow\SupportStrategy\SupportStrategyInterface: 'Symfony\Component\Workflow\SupportStrategy\WorkflowSupportStrategyInterface'
        Symfony\Component\Workflow\SupportStrategy\ClassInstanceSupportStrategy: 'Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy'
