services:
    Rector\Rector\MagicDisclosure\GetAndSetToMethodCallRector:
        Enlight_View_Default:
            get: 'getAssign'
            set: 'assign'
        Enlight_Components_Session_Namespace:
            get: 'get'
            set: 'offsetSet'
        Shopware_Components_Config:
            get: 'offsetGet'
            set: 'offsetSet'
    Rector\Rector\MagicDisclosure\UnsetAndIssetToMethodCallRector:
        Enlight_Components_Session_Namespace:
            isset: 'offsetExists'
            unset: 'offsetUnset'
        Shopware_Components_Config:
            isset: 'offsetExists'
            unset: 'offsetUnset'