services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Utils\RectorGenerator\:
        resource: '../src'
        exclude:
            - '../src/Exception/*'
            - '../src/ValueObject/*'

parameters:
    rector_recipe: []
#        # run "bin/rector create" to create a new Rector + tests from this config
#        package: "Celebrity"
#        name: "SplitToExplodeRector"
#        node_types:
#            # put main node first, it is used to create namespace
#            - ""
#
#        description: "Removes unneeded $a = $a assigns"
#        code_before: >
#            <?php
#
#            class SomeClass
#            {
#                public function run()
#                {
#                    $a = $a;
#                }
#            }
#
#        code_after: >
#            <?php
#
#            class SomeClass
#            {
#                public function run()
#                {
#                }
#            }
#
#        source: # e.g. link to RFC or headline in upgrade guide, 1 or more in the list
#            - ""
#        set: "" # e.g. symfony30, target config to append this rector to
