parameters:
    # customizable (via %ENV()?)
    pharName: 'build/rector.phar'
    binFileName: 'bin/rector'
    buildDirectory: '%kernel.root_dir%/../../../../build-phar'

services:
    _defaults:
        autowire: true
        bind:
            $pharName: '%pharName%'
            $binFileName: '%binFileName%'
            $buildDirectory: '%buildDirectory%'
        # for "bin/compile" fetching
        public: true

    Rector\PharBuilder\:
        resource: '../'

    # Symfony\Console
    Symfony\Component\Console\Application:
        calls:
            - ['add', ['@Rector\PharBuilder\Command\CompileCommand']]
            - ['setDefaultCommand', ['compile', true]]

    Symfony\Component\Console\Style\SymfonyStyle: ~

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput
