services:
    Rector\CodingStyle\Rector\If_\NullableCompareToNullRector: ~
    Rector\CodingStyle\Rector\FuncCall\SimpleArrayCallableToStringRector: ~
    Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector: ~
    Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector: ~
    Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector: ~
    Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector: ~

    # requires configuration
    # Rector\CodingStyle\Rector\ClassMethod\YieldClassMethodToArrayClassMethodRector: ~
    # Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector: ~
    Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector: ~
    Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector: ~
    Rector\CodingStyle\Rector\String_\SplitStringClassConstantToClassConstFetchRector: ~
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: ~

    # 'ClassName' â†’ ClassName::class
    Rector\Php55\Rector\String_\StringClassNameToClassConstantRector: ~
    Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector: ~
    Rector\CodingStyle\Rector\Include_\FollowRequireByDirRector: ~
    Rector\CodingStyle\Rector\Catch_\CatchExceptionNameMatchingTypeRector: ~
    Rector\CodingStyle\Rector\Assign\SplitDoubleAssignRector: ~

    Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector: ~
    Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector: ~
    Rector\CodingStyle\Rector\ClassMethod\NewlineBeforeNewAssignSetRector: ~
    Rector\CodingStyle\Rector\String_\ManualJsonStringToJsonEncodeArrayRector: ~
    Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector: ~
    Rector\CodingStyle\Rector\ClassMethod\MakeInheritedMethodVisibilitySameAsParentRector: ~
