services:
    Rector\CodingStyle\Rector\If_\NullableCompareToNullRector: null
    Rector\CodingStyle\Rector\FuncCall\SimpleArrayCallableToStringRector: null
    Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector: null
    Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector: null
    Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector: null
    Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector: null

    # requires configuration
    # Rector\CodingStyle\Rector\ClassMethod\YieldClassMethodToArrayClassMethodRector: null
    # Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector: null
    Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector: null
    Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector: null
    Rector\CodingStyle\Rector\String_\SplitStringClassConstantToClassConstFetchRector: null
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: null

    # 'ClassName' â†’ ClassName::class
    Rector\Php55\Rector\String_\StringClassNameToClassConstantRector: null
    Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector: null
    Rector\CodingStyle\Rector\Include_\FollowRequireByDirRector: null
    Rector\CodingStyle\Rector\Catch_\CatchExceptionNameMatchingTypeRector: null
    Rector\CodingStyle\Rector\Assign\UseIncrementAssignRector: null
    Rector\CodingStyle\Rector\Assign\SplitDoubleAssignRector: null

    Rector\CodingStyle\Rector\ClassConst\VarConstantCommentRector: null
    Rector\CodingStyle\Rector\Encapsed\EncapsedStringsToSprintfRector: null
    Rector\CodingStyle\Rector\ClassMethod\NewlineBeforeNewAssignSetRector: null
    Rector\CodingStyle\Rector\String_\ManualJsonStringToJsonEncodeArrayRector: null
    Rector\CodingStyle\Rector\Class_\AddArrayDefaultToArrayPropertyRector: null
    Rector\CodingStyle\Rector\ClassMethod\MakeInheritedMethodVisibilitySameAsParentRector: null
    Rector\CodingStyle\Rector\FuncCall\CallUserFuncCallToVariadicRector: null
    Rector\CodingStyle\Rector\FuncCall\VersionCompareFuncCallToConstantRector: null
    Rector\CodingStyle\Rector\FuncCall\FunctionCallToConstantRector:
        $functionsToConstants:
            php_sapi_name: PHP_SAPI
            pi: M_PI
    Rector\CodingStyle\Rector\Function_\CamelCaseFunctionNamingToUnderscoreRector: null
