# related: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md

services:
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'PhpCsFixer\Fixer\DefinedFixerInterface': 'PhpCsFixer\Fixer\FixerInterface'
            'PhpCsFixer\Fixer\ConfigurationDefinitionFixerInterface': 'PhpCsFixer\Fixer\ConfigurableFixerInterface'
    # merge interfaces
    # PhpCsFixer\Fixer\FixerInterface + PhpCsFixer\Fixer\DefinedFixerInterface => PhpCsFixer\Fixer\FixerInterface
