services:
    Rector\CodeQuality\Rector\Assign\CombinedAssignRector: null
    Rector\CodeQuality\Rector\BooleanAnd\SimplifyEmptyArrayCheckRector: null
    Rector\CodeQuality\Rector\Foreach_\ForeachToInArrayRector: null
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToCoalescingRector: null
    Rector\CodeQuality\Rector\FuncCall\InArrayAndArrayKeysToArrayKeyExistsRector: null
    Rector\CodeQuality\Rector\FuncCall\SimplifyFuncGetArgsCountRector: null
    Rector\CodeQuality\Rector\FuncCall\SimplifyInArrayValuesRector: null
    Rector\CodeQuality\Rector\FuncCall\SimplifyStrposLowerRector: null
    Rector\CodeQuality\Rector\Identical\GetClassToInstanceOfRector: null
    Rector\CodeQuality\Rector\Identical\SimplifyArraySearchRector: null
    Rector\CodeQuality\Rector\Identical\SimplifyConditionsRector: null
    Rector\CodeQuality\Rector\If_\SimplifyIfNotNullReturnRector: null
    Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector: null
    Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: null
    Rector\CodeQuality\Rector\Ternary\UnnecessaryTernaryExpressionRector: null

    Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector: null
    Rector\CodeQuality\Rector\BinaryOp\SimplifyDeMorganBinaryRector: null
    Rector\CodeQuality\Rector\Ternary\SimplifyTautologyTernaryRector: null
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToArrayFilterRector: null
    Rector\CodeQuality\Rector\FuncCall\SingleInArrayToCompareRector: null
    Rector\CodeQuality\Rector\If_\SimplifyIfElseToTernaryRector: null
    Rector\CodeQuality\Rector\Concat\JoinStringConcatRector: null
    Rector\CodeQuality\Rector\If_\ConsecutiveNullCompareReturnsToNullCoalesceQueueRector: null
    Rector\CodeQuality\Rector\If_\SimplifyIfIssetToNullCoalescingRector: null
    Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector: null
    Rector\CodeQuality\Rector\If_\CombineIfRector: null
    Rector\CodeQuality\Rector\Equal\UseIdenticalOverEqualWithSameTypeRector: null
    Rector\CodeQuality\Rector\Ternary\SimplifyDuplicatedTernaryRector: null
    Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector: null
    Rector\CodeQuality\Rector\FuncCall\SimplifyRegexPatternRector: null

    Rector\CodeQuality\Rector\Identical\BooleanNotIdenticalToNotIdenticalRector: null
    Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector: null
    Rector\CodeQuality\Rector\LogicalAnd\AndAssignsToSeparateLinesRector: null
    Rector\CodeQuality\Rector\For_\ForToForeachRector: null
    Rector\CodeQuality\Rector\FuncCall\CompactToVariablesRector: null
    Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector: null
    Rector\CodeQuality\Rector\FuncCall\IsAWithStringWithThirdArgumentRector: null
    Rector\CodeQuality\Rector\FuncCall\StrlenZeroToIdenticalEmptyStringRector: null
    Rector\CodeQuality\Rector\If_\RemoveAlwaysTrueConditionSetInConstructorRector: null
    Rector\CodeQuality\Rector\Catch_\ThrowWithPreviousExceptionRector: null
    Rector\CodeQuality\Rector\FuncCall\RemoveSoleValueSprintfRector: null
    Rector\CodeQuality\Rector\If_\ShortenElseIfRector: null
    Rector\SOLID\Rector\ClassMethod\UseInterfaceOverImplementationInConstructorRector: null
    Rector\CodeQuality\Rector\FuncCall\AddPregQuoteDelimiterRector: null
    Rector\CodeQuality\Rector\FuncCall\ArrayMergeOfNonArraysToSimpleArrayRector: null
    Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector: null
    Rector\CodeQuality\Rector\Ternary\ArrayKeyExistsTernaryThenValueToCoalescingRector: null
    Rector\CodeQuality\Rector\Include_\AbsolutizeRequireAndIncludePathRector: null
    Rector\CodeQuality\Rector\FuncCall\ChangeArrayPushToArrayAssignRector: null
    Rector\CodeQuality\Rector\For_\ForRepeatedCountToOwnVariableRector: null
    Rector\CodeQuality\Rector\Foreach_\ForeachItemsAssignToEmptyArrayToAssignRector: null
    Rector\CodeQuality\Rector\BinaryOp\InlineIfToExplicitIfRector: null
    Rector\CodeQuality\Rector\FuncCall\ArrayKeysAndInArrayToArrayKeyExistsRector: null
    Rector\CodeQuality\Rector\Assign\SplitListAssignToSeparateLineRector: null
    Rector\CodeQuality\Rector\Foreach_\UnusedForeachValueToArrayKeysRector: null
