imports:
    - { resource: 'phpunit-exception.yaml' }

services:
    # https://github.com/rectorphp/rector/issues/1024
    Rector\TypeDeclaration\Rector\ClassMethod\AddParamTypeDeclarationRector:
        $typehintForParameterByMethodByClass:
            PHPUnit\Framework\TestCase:
                __construct:
                    2: '' # no type, $dataName

    Rector\PHPUnit\Rector\MethodCall\SpecificAssertContainsRector: ~
    Rector\PHPUnit\Rector\MethodCall\SpecificAssertInternalTypeRector: ~

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            # https://github.com/sebastianbergmann/phpunit/issues/3123
            PHPUnit_Framework_MockObject_MockObject: 'PHPUnit\Framework\MockObject\MockObject'

    Rector\PHPUnit\Rector\MethodCall\AssertEqualsParameterToSpecificMethodsTypeRector: null

    Rector\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        $typehintForMethodByClass:
            PHPUnit\Framework\TestCase:
                setUpBeforeClass: 'void'
                setUp: 'void'
                assertPreConditions: 'void'
                assertPostConditions: 'void'
                tearDown: 'void'
                tearDownAfterClass: 'void'
                onNotSuccessfulTest: 'void'

    Rector\PHPUnit\Rector\MethodCall\ReplaceAssertArraySubsetRector: ~
