services:
    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            mysqli_param_count: 'mysqli_stmt_param_count'

    Rector\Php54\Rector\FuncCall\RemoveReferenceFromCallRector: ~
    Rector\Php54\Rector\Break_\RemoveZeroBreakContinueRector: ~
