services:
    Rector\Php74\Rector\Property\TypedPropertyRector: ~

    Rector\Rector\Function_\RenameFunctionRector:
        # https://wiki.php.net/rfc/deprecations_php_7_4#the_real_type
        is_real: 'is_float'
        # https://wiki.php.net/rfc/deprecations_php_7_4#apache_request_headers_function
        apache_request_headers: 'getallheaders'
        hebrevc: ['nl2br', 'hebrev']
    Rector\Php74\Rector\FuncCall\ArrayKeyExistsOnPropertyRector: ~
    Rector\Php74\Rector\FuncCall\FilterVarToAddSlashesRector: ~
    Rector\Php74\Rector\StaticCall\ExportToReflectionFunctionRector: ~
    Rector\Php74\Rector\MagicConstClass\ClassConstantToSelfClassRector: ~
    Rector\Php74\Rector\FuncCall\GetCalledClassToStaticClassRector: ~
    Rector\Php74\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector: ~
    Rector\Php74\Rector\Double\RealToFloatTypeCastRector: ~
    Rector\Php74\Rector\Assign\NullCoalescingOperatorRector: ~
    Rector\Php74\Rector\Function_\ReservedFnFunctionRector: ~
    Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector: ~
    Rector\Php74\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector: ~
    Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector: ~
