parameters:
    # PHP 7.2 "object" type hint
    enable_object_type: true

services:
    Rector\Php\Rector\Each\WhileEachToForeachRector: ~
    Rector\Php\Rector\Each\ListEachRector: ~
    Rector\Php\Rector\Unset_\UnsetCastRector: ~
    Rector\Php\Rector\ConstFetch\BarewordStringRector: ~

    Rector\Rector\Function_\FunctionReplaceRector:
        jpeg2wbmp: 'imagecreatefromjpeg' # and imagewbmp
        png2wbmp: 'imagecreatefrompng' # or imagewbmp
        # http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.gmp_random-function
        gmp_random: 'gmp_random_bits' # or gmp_random_range
        read_exif_data: 'exif_read_data'

    Rector\Php\Rector\FunctionLike\ParamScalarTypehintRector: ~
    Rector\Php\Rector\FunctionLike\ReturnScalarTypehintRector: ~
    Rector\Php\Rector\FuncCall\GetClassOnNullRector: ~
