services:
    Rector\Rector\Typehint\ParentTypehintedArgumentRector:
        'Doctrine\ORM\Mapping\ClassMetadataFactory':
            'setEntityManager':
                'em': 'Doctrine\ORM\EntityManagerInterface'
        'Doctrine\ORM\Tools\DebugUnitOfWorkListener':
            'dumpIdentityMap':
                'em': 'Doctrine\ORM\EntityManagerInterface'

    Rector\Rector\Argument\ArgumentRemoverRector:
        -
            class: 'Doctrine\ORM\Persisters\Entity\AbstractEntityInheritancePersister'
            method: 'getSelectJoinColumnSQL'
            position: 4

