services:
    Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\Closure\AddClosureReturnTypeRector: ~
    Rector\TypeDeclaration\Rector\ClassMethod\AddArrayParamDocTypeRector: ~
    Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector: ~
