# source: https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html
services:
    Rector\Rector\Property\PropertyToMethodRector:
        $perClassPropertyToMethods:
            Cake\Network\Request:
                params:
                    get:
                        method: 'getAttribute'
                        arguments: ['params']

                data:
                    get: 'getData'
                query:
                    get: 'getQueryParams'
                cookies:
                    get: 'getCookie'
                base:
                    get:
                        method: 'getAttribute'
                        arguments: ['base']
                webroot:
                    get:
                        method: 'getAttribute'
                        arguments: ['webroot']
                here:
                    get:
                        method: 'getAttribute'
                        arguments: ['here']

    Rector\Rector\Property\RenamePropertyRector:
        $oldToNewPropertyByTypes:
            Cake\Network\Request:
                _session: 'session'

    Rector\CakePHP\Rector\MethodCall\ModalToGetSetRector:
        $methodNamesByTypes:
            Cake\Core\InstanceConfigTrait:
                config:
                    minimal_argument_count: 2
                    first_argument_type_to_set: array
            Cake\Core\StaticConfigTrait:
                config:
                    minimal_argument_count: 2
                    first_argument_type_to_set: array
                dsnClassMap: null
            Cake\Console\ConsoleOptionParser:
                command: null
                description: null
                epilog: null
            Cake\Database\Connection:
                driver: null
                schemaCollection: null
                useSavePoints:
                    set: 'enableSavePoints'
                    get: 'isSavePointsEnabled'
            Cake\Database\Driver:
                autoQuoting:
                    set: 'enableAutoQuoting'
                    get: 'isAutoQuotingEnabled'
            Cake\Database\Expression\FunctionExpression:
                name: null
            Cake\Database\Expression\QueryExpression:
                tieWith:
                    set: 'setConjunction'
                    get: 'getConjunction'
            Cake\Database\Expression\ValuesExpression:
                columns: null
                values: null
                query: null
            Cake\Database\Query:
                connection: null
                selectTypeMap: null
                bufferResults:
                    set: 'enableBufferedResults'
                    get: 'isBufferedResultsEnabled'
            Cake\Database\Schema\CachedCollection:
                cacheMetadata: null
            Cake\Database\Schema\TableSchema:
                options: null
                temporary:
                    set: 'setTemporary'
                    get: 'isTemporary'
            Cake\Database\TypeMap:
                defaults: null
                types: null
            Cake\Database\TypeMapTrait:
                typeMap: null
                defaultTypes: null
            Cake\ORM\Association:
                name: null
                cascadeCallbacks: null
                source: null
                target: null
                conditions: null
                bindingKey: null
                foreignKey: null
                dependent: null
                joinType: null
                property: null
                strategy: null
                finder: null
            Cake\ORM\Association\BelongsToMany:
                targetForeignKey: null
                saveStrategy: null
                conditions: null
            Cake\ORM\Association\HasMany:
                saveStrategy: null
                foreignKey: null
                sort: null
            Cake\ORM\Association\HasOne:
                foreignKey: null
            Cake\ORM\EagerLoadable:
                config: null
                canBeJoined:
                    set: 'setCanBeJoined'
                    get: 'canBeJoined'
            Cake\ORM\EagerLoader:
                matching:
                    set: 'setMatching'
                    get: 'getMatching'
                    # note: will have to be called after setMatching() to keep the old behavior
                    # ref: https://github.com/cakephp/cakephp/blob/4feee5463641e05c068b4d1d31dc5ee882b4240f/src/ORM/EagerLoader.php#L330
                autoFields:
                    set: 'enableAutoFields'
                    get: 'isAutoFieldsEnabled'
            Cake\ORM\Locator\TableLocator:
                config: null
            Cake\ORM\Query:
                eagerLoader: null
                hydrate:
                    set: 'enableHydration'
                    get: 'isHydrationEnabled'
                autoFields:
                    set: 'enableAutoFields'
                    get: 'isAutoFieldsEnabled'
            Cake\ORM\Table:
                table: null
                alias: null
                registryAlias: null
                connection: null
                schema: null
                primaryKey: null
                displayField: null
                entityClass: null
            Cake\Mailer\Email:
                from: null
                sender: null
                replyTo: null
                readReceipt: null
                returnPath: null
                to: null
                cc: null
                bcc: null
                charset: null
                headerCharset: null
                emailPattern: null
                subject: null
                # template: have to be changed manually, non A â†’ B change + array case
                viewRender:
                    set: 'setViewRenderer'
                    get: 'getViewRenderer'
                viewVars: null
                theme: null
                helpers: null
                emailFormat: null
                transport: null
                messageId: null
                domain: null
                attachments: null
                configTransport: null
                profile: null
            Cake\Validation\Validator:
                provider: null
            Cake\View\StringTemplateTrait:
                templates: null
            Cake\View\ViewBuilder:
                templatePath: null
                layoutPath: null
                plugin: null
                helpers: null
                theme: null
                template: null
                layout: null
                options: null
                name: null
                className: null
                autoLayout:
                    set: 'enableAutoLayout'
                    get: 'isAutoLayoutEnabled'

    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            Cake\Network\Request:
                param: 'getParam'
                data: 'getData'
                query: 'getQuery'
                cookie: 'getCookie'
                method: 'getMethod'
                setInput: 'withBody'
            Cake\Network\Response:
                location: 'withLocation'
                disableCache: 'withDisabledCache'
                type: 'withType'
                charset: 'withCharset'
                cache: 'withCache'
                modified: 'withModified'
                expires: 'withExpires'
                sharable: 'withSharable'
                maxAge: 'withMaxAge'
                vary: 'withVary'
                etag: 'withEtag'
                compress: 'withCompression'
                length: 'withLength'
                mustRevalidate: 'withMustRevalidate'
                notModified: 'withNotModified'
                cookie: 'withCookie'
                file: 'withFile'
                download: 'withDownload'
                # psr-7
                header: 'getHeader'
                body: 'withBody'
                statusCode: 'getStatusCode'
                protocol: 'getProtocolVersion'
            Cake\Event\Event:
                'name': 'getName'
                'subject': 'getSubject'
                'result': 'getResult'
                'data': 'getData'
            Cake\View\Helper\FormHelper:
                input: 'control'
                inputs: 'controls'
                allInputs: 'allControls'
            Cake\Mailer\Mailer:
                layout: 'setLayout'
            Cake\Routing\Route\Route:
                parse: 'parseRequest'
            Cake\Routing\Router:
                parse: 'parseRequest'

    Rector\Rector\Visibility\ChangeMethodVisibilityRector:
        $methodToVisibilityByClass:
            Cake\Mailer\MailerAwareTrait:
                getMailer: 'protected'
            Cake\View\CellTrait:
                cell: 'protected'

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            Cake\Database\Schema\Table: 'Cake\Database\Schema\TableSchema'

    Rector\Rector\MethodBody\NormalToFluentRector:
        $fluentMethodsByType:
            Cake\Network\Response:
                # https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#adopting-immutable-responses
                # renames are done by RenameMethodRector above
                - 'withLocation'
                - 'withHeader'
                - 'withLocation'
                - 'withDisabledCache'
                - 'withType'
                - 'withCharset'
                - 'withCache'
                - 'withModified'
                - 'withExpires'
                - 'withSharable'
                - 'withMaxAge'
                - 'withVary'
                - 'withEtag'
                - 'withCompression'
                - 'withLength'
                - 'withMustRevalidate'
                - 'withNotModified'
                - 'withCookie'
                - 'withFile'
                - 'withDownload'

    # @todo
    # The fieldList option for Cake\ORM\Table::newEntity() and patchEntity() has been renamed to fields to be more consistent with other parts of the ORM.
