rectors:
    Rector\Rector\Dynamic\ParentTypehintedArgumentRector:
        'Doctrine\ORM\Mapping\ClassMetadataFactory':
            'setEntityManager':
                'em': 'Doctrine\ORM\EntityManagerInterface'
        'Doctrine\ORM\Tools\DebugUnitOfWorkListener':
            'dumpIdentityMap':
                'em': 'Doctrine\ORM\EntityManagerInterface'

    Rector\Rector\Dynamic\ArgumentReplacerRector:
        'Doctrine\ORM\Persisters\Entity\AbstractEntityInheritancePersister':
            'getSelectJoinColumnSQL':
                4:
                    ~: ~
