services:
    Rector\Symfony\Rector\Validator\ConstraintUrlOptionRector: ~
    Rector\Symfony\Rector\Form\FormIsValidRector: ~
    Rector\Symfony\Rector\Form\StringFormTypeToClassRector: ~
    Rector\Symfony\Rector\VarDumper\VarDumperTestTraitMethodArgsRector: ~
    Rector\Symfony\Rector\DependencyInjection\ContainerBuilderCompileEnvArgumentRector: ~

    Rector\Symfony\Rector\Process\ProcessBuilderInstanceRector: ~
    Rector\Symfony\Rector\Process\ProcessBuilderGetProcessRector: ~

    Rector\Rector\Class_\RenameClassRector:
        'Symfony\Component\Validator\Tests\Constraints\AbstractConstraintValidatorTest': 'Symfony\Component\Validator\Test\ConstraintValidatorTestCase'
        'Symfony\Component\Process\ProcessBuilder': 'Symfony\Component\Process\Process'
