services:
    Rector\Rector\Contrib\Symfony\Validator\ConstraintUrlOptionRector: ~
    Rector\Rector\Contrib\Symfony\Form\FormIsValidRector: ~
    Rector\Rector\Contrib\Symfony\Form\StringFormTypeToClassRector: ~
    Rector\Rector\Contrib\Symfony\VarDumper\VarDumperTestTraitMethodArgsRector: ~
    Rector\Rector\Contrib\Symfony\DependencyInjection\ContainerBuilderCompileEnvArgumentRector: ~

    Rector\Rector\Contrib\Symfony\Process\ProcessBuilderInstanceRector: ~
    Rector\Rector\Contrib\Symfony\Process\ProcessBuilderGetProcessRector: ~

    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'Symfony\Component\Validator\Tests\Constraints\AbstractConstraintValidatorTest': 'Symfony\Component\Validator\Test\ConstraintValidatorTestCase'
            'Symfony\Component\Process\ProcessBuilder': 'Symfony\Component\Process\Process'
