services:
    _defaults:
        public: true
        autowire: true

    Rector\Core\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/Testing/PHPUnit/*'
            - '../src/Testing/Dumper/*'
            - '../src/RectorDefinition/*'
            - '../src/Exception/*'
            - '../src/DependencyInjection/CompilerPass/*'
            - '../src/DependencyInjection/Loader/*'
            - '../src/HttpKernel/*'
            - '../src/ValueObject/*'

    Symfony\Component\Console\Application:
        alias: 'Rector\Core\Console\Application'

    Symfony\Component\Console\Descriptor\TextDescriptor: null

    # PhpParser - Parser
    PhpParser\ParserFactory: null
    PhpParser\BuilderFactory: null
    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeFinder: null

    # value resolver
    Symfony\Component\Filesystem\Filesystem: null
    Symplify\PackageBuilder\Reflection\PrivatesAccessor: null

    Symplify\PackageBuilder\FileSystem\FileSystem: null
    Symplify\SmartFileSystem\Finder\FinderSanitizer: null

    Symplify\PackageBuilder\Parameter\ParameterProvider: null
    Symplify\PackageBuilder\Reflection\PrivatesCaller: null
    Symplify\PackageBuilder\Strings\StringFormatConverter: null

    # alises
    Symfony\Contracts\EventDispatcher\EventDispatcherInterface: '@Rector\Core\EventDispatcher\AutowiredEventDispatcher'

    OndraM\CiDetector\CiDetector: null

    # see https://github.com/symplify/packagebuilder#prevent-parameter-typos
    Symplify\PackageBuilder\EventSubscriber\ParameterTypoProofreaderEventSubscriber: null
    Symplify\PackageBuilder\Parameter\ParameterTypoProofreader:
        $correctToTypos:
            # keep "exclude_" explicit, to get typos to the correct key
            exclude_paths:
                - 'exclude'
                - 'excluded'
                - 'exclude_path'
                - 'excluded_path'
                - 'exclude_dir'
                - 'excluded_dir'
                - 'exclude_dirs'
                - 'excluded_dirs'
                - 'exclude_file'
                - 'excluded_file'
                - 'exclude_files'
                - 'excluded_files'
                - 'ignore_path'
                - 'ignored_path'
                - 'ignore_paths'
                - 'ignored_paths'
                - 'ignore_dir'
                - 'ignored_dir'
                - 'ignore_dirs'
                - 'ignored_dirs'
                - 'ignore_file'
                - 'ignored_file'
                - 'ignore_files'
                - 'ignored_files'
                - 'skip_path'
                - 'skip_paths'
                - 'skip_dir'
                - 'skip_dirs'
                - 'skip_file'
                - 'skip_files'
            exclude_rectors:
                - 'exclude_rector'
                - 'excluded_rector'
                - 'excluded_rectors'
                - 'skip_rector'
                - 'skip_rectors'
            autoload_paths:
                # https://regex101.com/r/aXEZYk/1
                - '#(autolaod|autoload|include|bootstrap)((ed)?_(path(s)?|dir(s)?|file(s)?))?#'
            auto_import_names:
                - 'auto_imort_names'
                - 'auto_names'
                - 'import_name(space)?(s)?'
