rectors:
    Rector\Rector\Contrib\PHPUnit\ExceptionAnnotationRector: ~
    Rector\Rector\Contrib\PHPUnit\GetMockRector: ~
    Rector\Rector\Contrib\PHPUnit\SpecificMethodRector: ~

    # ref. https://github.com/sebastianbergmann/phpunit/compare/5.7.9...6.0.0
    Rector\Rector\Dynamic\PseudoNamespaceToNamespaceRector:
        - 'PHPUnit_'

    # handles 2nd and 3rd arugment of setExpectedException
    Rector\Rector\Contrib\PHPUnit\ExceptionRector: ~

    Rector\Rector\Dynamic\MethodNameReplacerRector:
        'PHPUnit\Framework\TestClass':
            'setExpectedException': 'expectedException'
            'setExpectedExceptionRegExp': 'expectedException'
