name: Tests

on: [pull_request, push]

jobs:
    finalize_classes:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.1', '7.2']

        name: "PHP ${{ matrix.php_version }}"

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            # Use library versions compatible with PHP 7.1
            -   run: |
                    mkdir temp && cd temp
                    composer require "doctrine/orm:~2.7.5" --ansi --no-interaction
                    composer require "phpunit/phpunit:~7.5" --dev --ansi --no-interaction

            -   run: vendor/bin/phpunit
