services:
    # order matters, this needs to be first to correctly detect parent repository
    Rector\Rector\Architecture\RepositoryAsService\ReplaceParentRepositoryCallsByRepositoryPropertyRector: ~

    Rector\Rector\Architecture\RepositoryAsService\MoveRepositoryFromParentToConstructorRector: ~

    Rector\Rector\Architecture\RepositoryAsService\ServiceLocatorToDIRector: ~

    # default mapper
    Rector\Bridge\DefaultDoctrineEntityAndRepositoryMapper: ~
