services:
    Rector\DeadCode\Rector\Stmt\RemoveDeadStmtRector: null
    Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector: null
    Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector: null
    Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector: null
    Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector: null
    Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector: null
    Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector: null
    Rector\DeadCode\Rector\ClassConst\RemoveUnusedPrivateConstantRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector: null
    Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector: null
    Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector: null
    Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector: null
    Rector\DeadCode\Rector\BooleanAnd\RemoveAndTrueRector: null
    Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector: null
    Rector\DeadCode\Rector\Concat\RemoveConcatAutocastRector: null

    Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: null
    Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector: null
    Rector\DeadCode\Rector\Instanceof_\RemoveDuplicatedInstanceOfRector: null
    Rector\DeadCode\Rector\Switch_\RemoveDuplicatedCaseInSwitchRector: null
    Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector: null
    Rector\DeadCode\Rector\Class_\RemoveSetterOnlyPropertyAndMethodCallRector: null

    Rector\DeadCode\Rector\Property\RemoveNullPropertyInitializationRector: null
    Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector: null
    Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector: null
    Rector\DeadCode\Rector\Ternary\TernaryToBooleanOrFalseToBooleanAndRector: null
    Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector: null
    Rector\DeadCode\Rector\TryCatch\RemoveDeadTryCatchRector: null
    Rector\DeadCode\Rector\ClassConst\RemoveUnusedClassConstantRector: null
    Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector: null
