services:
    Rector\DeadCode\Rector\Stmt\RemoveDeadStmtRector: ~
    Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector: ~
    Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector: ~
    Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector: ~
    Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector: ~
    Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector: ~
    Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector: ~
    Rector\DeadCode\Rector\ClassConst\RemoveUnusedPrivateConstantRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector: ~
    Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector: ~
    Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector: ~
    Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector: ~
    Rector\DeadCode\Rector\BooleanAnd\RemoveAndTrueRector: ~
    Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector: ~
    Rector\DeadCode\Rector\Concat\RemoveConcatAutocastRector: ~

    Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector: ~
    Rector\DeadCode\Rector\Instanceof_\RemoveDuplicatedInstanceOfRector: ~
    Rector\DeadCode\Rector\Switch_\RemoveDuplicatedCaseInSwitchRector: ~
    Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector: ~
    Rector\DeadCode\Rector\Class_\RemoveSetterOnlyPropertyAndMethodCallRector: ~

    Rector\DeadCode\Rector\Property\RemoveNullPropertyInitializationRector: ~
    Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector: ~
    Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector: ~
    Rector\DeadCode\Rector\Ternary\TernaryToBooleanOrFalseToBooleanAndRector: ~
    Rector\DeadCode\Rector\FunctionLike\RemoveUnusedElseForReturnedValueRector: ~
