services:
    _defaults:
        public: true
        autowire: true

    Rector\MagicDisclosure\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/ValueObject/*'
