services:
    _defaults:
        public: true
        autowire: true

    Rector\ConsoleDiffer\:
        resource: '../src'

    Rector\ConsoleDiffer\DifferAndFormatter:
        $differ: '@differ'

    Rector\ConsoleDiffer\MarkdownDifferAndFormatter:
        $markdownDiffer: '@markdownDiffer'

    # differ
    diffOutputBuilder:
        class: SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    differ:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@diffOutputBuilder'

    # makrdown differ
    markdownDiffOutputBuilder:
        class: SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder
        factory: ['@Rector\ConsoleDiffer\Diff\Output\CompleteUnifiedDiffOutputBuilderFactory', 'create']

    markdownDiffer:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@markdownDiffOutputBuilder'
