imports:
    - { resource: 'nette-30/*' }

services:
    # Control class has remove __construct(), e.g. https://github.com/Pixidos/GPWebPay/pull/16/files#diff-fdc8251950f85c5467c63c249df05786
    Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: null

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            # nextras/forms was split into 2 packages
            Nextras\FormComponents\Controls\DatePicker: 'Nextras\FormComponents\Controls\DateControl'

            # @see https://github.com/nette/di/commit/a0d361192f8ac35f1d9f82aab7eb351e4be395ea
            Nette\DI\ServiceDefinition: 'Nette\DI\Definitions\ServiceDefinition'
            Nette\DI\Statement: 'Nette\DI\Definitions\Statement'

    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            # see https://github.com/nette/forms/commit/b99385aa9d24d729a18f6397a414ea88eab6895a
            Nette\Forms\Controls\BaseControl:
                setType: 'setHtmlType'
                setAttribute: 'setHtmlAttribute'

            # see https://github.com/nette/di/commit/1705a5db431423fc610a6f339f88dead1b5dc4fb
            Nette\DI\Definitions\ServiceDefinition:
                setClass: 'setType'
                getClass: 'getType'

            Nette\DI\Definitions\Definition:
                isAutowired: 'getAutowired'

    Rector\Nette\Rector\MethodCall\AddDatePickerToDateControlRector: null
    Rector\Nette\Rector\MethodCall\SetClassWithArgumentToSetFactoryRector: null
