rectors:
    # dependency-injection
    Rector\Rector\Dynamic\ArgumentReplacerRector:
        -
            class: Symfony\Component\DependencyInjection\ContainerBuilder
            method: addCompilerPass
            position: 2
            type: added
            default_value: 0
