services:
    Rector\DeadCode\Rector\Stmt\RemoveDeadStmtRector: ~
    Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector: ~
    Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector: ~
    Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector: ~
    Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector: ~
    Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector: ~
    Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveOverriddenValuesRector: ~
    Rector\DeadCode\Rector\ClassConst\RemoveUnusedPrivateConstantRector: ~
    Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector: ~
    Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector: ~
