services:
    Rector\Privatization\Rector\ClassMethod\PrivatizeLocalOnlyMethodRector: null
    Rector\Privatization\Rector\MethodCall\PrivatizeLocalGetterToPropertyRector: null
    Rector\Privatization\Rector\Property\PrivatizeLocalPropertyToPrivatePropertyRector: null
