services:
    Rector\Privatization\Rector\ClassMethod\PrivatizeLocalOnlyMethodRector: null
    Rector\Privatization\Rector\MethodCall\PrivatizeLocalGetterToPropertyRector: null
    Rector\Privatization\Rector\Property\PrivatizeLocalPropertyToPrivatePropertyRector: null
    Rector\Privatization\Rector\ClassConst\PrivatizeLocalClassConstantRector: null
    Rector\Privatization\Rector\Property\PrivatizeFinalClassPropertyRector: null
