name: Rector Run

on:
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            # The Symfony Polyfill libraries are needed
            -   run: composer require symfony/polyfill-php72 symfony/polyfill-php73 symfony/polyfill-php74 symfony/polyfill-php80 --no-install --no-update

            # Execute the downgrade script
            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # Upload the artifact so we can download and review the downgraded code
            -   run: mkdir build
            -   uses: montudor/action-zip@v0.1.1
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build** ci** tests** "**/tests**"

            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-downgraded-code
                    path: build/rector-php71.zip

            # Run all the tests on PHP 7.4 (because JUnit needs PHP 7.3+),
            # but using Rector downgraded to PHP 7.1
            -   run: vendor/bin/phpunit

            # Avoid Composer v2 platform checks (composer.json requires PHP 7.3+, but below we are running 7.1)
            -   run: composer config platform-check false
            # Regenerating the autoload files will remove vendor/composer/platform_check.php, otherwise executing bin/rector on 7.1 fails
            -   run: composer dumpautoload

            # Remove DEV dependencies
            -   run: composer install --no-dev

            # Replace the composer.json file
            -   run: cp ci/downgrade/composer.json ./composer.json

            # Rector without DEV needs phpstan.neon removed
            -   run: rm phpstan.neon
            -   run: rm phpstan-for-rector.neon

            # Override the artifact with downgraded Composer too
            -   run: rm build/rector-php71.zip
            -   uses: montudor/action-zip@v0.1.1
                with:
                    args: zip -X -r build/rector-php71.zip . -x *.git* .* "*/\.*" build**
            -   uses: actions/upload-artifact@v2
                with:
                    name: rector-downgraded-code
                    path: build/rector-php71.zip

            # Switch to PHP 7.1 and run PHPStan to analyze the code,
            # as to make sure no 7.2+ code was left behind (if there is, PHP will throw some error)
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            # Test the downgraded Rector by running the default set on its own src
            -   run: bin/rector process rules/downgrade-php70/src

            # Run PHPStan to make sure no PHP 7.2+ code was left behind
            -   run: vendor/bin/phpstan analyse -c ci/downgrade/phpstan.neon --ansi

            # If we reach here the downgrade works! Then, deploy it to its own repo
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            # Copy all files for the target repo to rector-downgrade/
            # Remove the artifact
            -   run: rm build/rector-php71.zip
            -   run: rm -R build
            # Copy all files
            -   run: rsync -av * rector-downgrade --quiet
            # Set-up own workflows for target repo
            -   run: cp -R ci/downgrade/target-repo/. rector-downgrade/

            # publish it to remote repository
            -
                uses: symplify/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'rector-downgrade'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: 'rector-php71'
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
