# builds the content of https://github.com/rectorphp/rector-prefixed
name: Build Scoped Rector

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build_scoped_rector:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

                # fixes https://github.com/rectorphp/rector/pull/4559/checks?check_run_id=1359814403, see https://github.com/shivammathur/setup-php#composer-github-oauth
                env:
                    COMPOSER_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            # install only prod dependencies - do not use ramsey, it uses cache including "dev", we want to avoid it here
            -   run: composer install --no-dev --ansi

            # 1. copy files to $NESTED_DIRECTORY directory Exclude the scoped/nested directories to prevent rsync from copying in a loop
            -  run: rsync --exclude rector-build -av * rector-build --quiet
            -  run: rm -rf rector-build/packages-tests rector-build/rules-tests rector-build/tests

            # 2. downgrade rector
            -   run: sh build/downgrade-rector.sh rector-build

            # 3. prefix classes
            -   run: sh build/build-rector-scoped.sh rector-build rector-prefixed-downgraded

            # 4. lint the code for PHP 7.1 - this must happen here, as setup-php allows only one PHP version switch: https://github.com/shivammathur/setup-php/issues/434
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none
            -   run: composer create-project php-parallel-lint/php-parallel-lint php-parallel-lint --ansi
            -   run: php-parallel-lint/parallel-lint rector-prefixed-downgraded --exclude rector-prefixed-downgraded/stubs --exclude rector-prefixed-downgraded/vendor/symfony/polyfill-intl-grapheme/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill-mbstring/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/error-handler/Resources --exclude rector-prefixed-downgraded/vendor/symfony/http-kernel/Resources --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Mbstring/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Apcu/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Iconv/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Intl/Idn/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Intl/Normalizer/bootstrap80.php --exclude rector-prefixed-downgraded/vendor/symfony/polyfill/src/Intl/Grapheme/bootstrap80.php

            # 5. copy repository meta files
            -   run: cp -R build/target-repository/. rector-prefixed-downgraded

            # 6. publish it to remote repository without tag
            -
                uses: symplify/github-action-monorepo-split@1.1
                if: "!startsWith(github.ref, 'refs/tags/')"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'rector-prefixed-downgraded'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: 'rector-prefixed'
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"

            # 7. publish it to remote repository with tag
            -
                uses: symplify/github-action-monorepo-split@1.1
                if: "startsWith(github.ref, 'refs/tags/')"
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'rector-prefixed-downgraded'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: 'rector-prefixed'
                    tag: ${GITHUB_REF#refs/tags/}
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
