name: CI Review

on:
    pull_request: null

jobs:
    ci_review:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Validate Monorepo"
                        write_run: "composer propagate --ansi"
                        commit_message: "propagate monorepo dependencies"
                        check_run: "composer validate-monorepo --ansi"

                    -
                        name: "Sync Doctrine Annotation Parser"
                        write_run: "bin/rector sync-annotation-parser --ansi"
                        commit_message: "sync doctrine/annotations parser"
                        check_run: "bin/rector sync-annotation-parser --dry-run --ansi"

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v1

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.write_run }}

            # see https://github.com/EndBug/add-and-commit
            -
                uses: EndBug/add-and-commit@v5
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: 'packages'
                    message: '[ci-review] ${{ matrix.actions.commit_message }}'
                    author_name: rector-bot
                    author_email: tomas@getrector.org
                env:
                    # to get push access
                    token: ${{ secrets.ACCESS_TOKEN }}

            -   run: ${{ matrix.actions.check_run }}
