name: Code Analysis

on:
    pull_request: null

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Show command'
                        run: bin/rector show --ansi

                    -
                        name: Validate Fixtures
                        run: bin/rector validate-fixture-suffix --ansi

                    -
                        name: Validate Fixtures Namespace
                        run: bin/rector validate-fixture-namespace --ansi

                    -
                        name: Validate Fixtures class name
                        run: bin/rector validate-fixture-classname --ansi

                    -
                        name: Validate Fixtures file name
                        run: bin/rector validate-fixture-filename --ansi

                    # make sure skipped files have "skip_" prefix
                    -
                        name: Validate Fixtures skip file prefix
                        run: vendor/symplify/easy-testing/bin/easy-testing validate-fixture-skip-naming rules tests

                    -
                        name: 'Validate Sets Loading'
                        # this is very slow, so it has to be in own workflow
                        run: bin/rector validate-sets --ansi

                    -
                        name: 'Validate PHPStan Mappers Compatibility'
                        run: bin/rector check-static-type-mappers --ansi

                    -
                        name: 'Validate Max File Length'
                        run: vendor/bin/easy-ci validate-file-length packages rules src tests

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
