name: Code Analysis

on:
    # tempoarry disable for this PR
    #    pull_request: null

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'PHPStan for config'
                        run: composer phpstan-config

                    -
                        name: 'Show command'
                        run: bin/rector show --config rector-ci.php --ansi

                    -
                        name: Validate Fixtures
                        run: bin/rector validate-fixture-suffix --ansi

                    -
                        name: Validate Fixtures Namespace
                        run: bin/rector validate-fixture-namespace --ansi

                    -
                        name: Validate Fixtures class name
                        run: bin/rector validate-fixture-classname --ansi

                    -
                        name: 'Validate Sets Loading'
                        # this is very slow, so it has to be in own workflow
                        run: bin/rector validate-sets --ansi

                    -
                        name: 'Validate PHPStan Types Compatibility'
                        run: bin/rector sync-types --ansi

                    -
                        name: 'Validate PHPStan Mappers Compatibility'
                        run: bin/rector check-static-type-mappers --ansi

                    -
                        name: 'PHP Linter'
                        run: vendor/bin/parallel-lint src bin/rector config tests packages rules --exclude packages/rector-generator/templates --colors --exclude rules/psr4/tests/Rector/Namespace_/MultipleClassFileToPsr4ClassesRector/Source --exclude rules/autodiscovery/tests/Rector/FileNode/MoveInterfacesToContractNamespaceDirectoryRector/Expected

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
