# This workflow runs system tests: Use the Rector application from the source
# checkout to process "fixture" projects in tests/system-tests
# to see if those can be processed successfully
name: End to End tests on PHP 7.4

on:
    push:
        branches:
            - main

jobs:
    end_to_end_on_php74:
        runs-on: ubuntu-latest

        name: End to end test - PHP 7.4 and Match class name

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.4"
                    coverage: none

            -
                run: composer require rector/rector:dev-main --dev
                working-directory: e2e/parse-match-class-on-php74

            -
                run: vendor/bin/rector process --ansi
                working-directory: e2e/parse-match-class-on-php74
