name: End to End tests on PHP 7.2

on:
    push:
        branches:
            - main

jobs:
    end_to_end_on_php72:
        runs-on: ubuntu-latest

        name: End to end test - PHP 7.2 with load ReflectionUnionType stub

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.2"
                    coverage: none

            # wait for deploy to packagist
            -   run: sleep 40

            -
                run: composer require rector/rector:dev-main --ansi
                working-directory: e2e/reflection-union-php72

            -
                run: vendor/bin/rector process --ansi
                working-directory: e2e/reflection-union-php72
