name: Monorepo Split Packages

on:
    push:
        branches:
            - master

jobs:
    monorepo_split_packages:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package_name:
                    - simple-php-doc-parser
                    - symfony-php-config

        name: Monorepo Split of ${{ matrix.package_name }}

        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            # see https://github.com/TomasVotruba/github-action-monorepo-split
            -
                uses: TomasVotruba/github-action-monorepo-split@master
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package_name }}'
                    split-repository-organization: 'rectorphp'
                    split-repository-name: '${{ matrix.package_name }}'
                    tag: ${{ steps.previous_tag.outputs.tag }}
