name: Rector parallel

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    rector_parallel:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: bin/rector process --config rector-ci.yaml --dry-run
            -   run: bin/rector process --config rector-ci.yaml --dry-run --clear-cache --parallel --parallel-processes=2
            -   run: bin/rector process --config rector-ci.yaml --dry-run --clear-cache --parallel --parallel-processes=3
            -   run: bin/rector process --config rector-ci.yaml --dry-run --clear-cache --parallel --parallel-processes=4
            -   run: bin/rector process --config rector-ci.yaml --dry-run --clear-cache --parallel --parallel-processes=8
            -   run: bin/rector process --config rector-ci.yaml --dry-run --clear-cache --parallel --parallel-processes=16
