name: SonarCube

on: push

jobs:
    sonnar_cloud:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    # sonar needs non-shallow clone
                    fetch-depth: 10000
            -   uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
