name: Standalone Run

on:
    pull_request: null

jobs:
    standalone_run:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"
                    tools: composer:v1

            # see https://github.com/rlespinasse/github-slug-action
            -   name: Inject slug/short variables
                uses: rlespinasse/github-slug-action@v2.x

            # wait till packagist gets information about new branches
            -   run: sleep 15

            -   run:
                    # 1. install locally
                    mkdir test-paths
                    cd test-paths

                    # 2. install rector to "rector-dir"
                    mkdir rector-dir
                    composer require rector/rector:dev-${{ env.GITHUB_REF_SLUG_URL }}#${GITHUB_SHA} -d rector-dir --no-progress --ansi

                    # 3. download symfony demo to "symfony-demo-dir"
                    mkdir symfony-demo-dir
                    composer create-project symfony/symfony-demo symfony-demo-dir --dev --no-progress --ansi

                    # missing for some reason
                    composer require doctrine/doctrine-fixtures-bundle -d symfony-demo-dir --no-progress --ansi
                    composer dump-autoload --no-dev -d symfony-demo-dir --ansi

                    # 4. run an another project
                    rector-dir/vendor/bin/rector --ansi

                    cd symfony-demo-dir
                    ../rector-dir/vendor/bin/rector --ansi

                    # autoload errors due to remove --dev and mixed dependencies in /src and /tests
                    ../rector-dir/vendor/bin/rector process src --set code-quality --ansi
