name: Standalone Rule Test

on:
    push:
        branches:
            - main

jobs:
    standalone_rule_test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.3']
                directory:
                    - 'e2e/rector-prefixed-rule-test'

        name: End to end test - ${{ matrix.directory }}

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            # wait for deploy to packagist
            -   run: sleep 40

            -
                run: composer install --ansi
                working-directory: ${{ matrix.directory }}

            -
                run: vendor/bin/phpunit
                working-directory: ${{ matrix.directory }}
