name: Test With Drupal

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_with_drupal:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # 1. install locally
                    mkdir test-paths
                    cd test-paths

                    # Install latest Rector
                    mkdir rector-dir
                    composer require rector/rector:@dev -d rector-dir --no-progress

                    # Install Drupal
                    mkdir drupal-dir
                    composer create-project drupal/recommended-project drupal-dir --dev --no-progress

                    # missing for some reason
                    # composer require doctrine/doctrine-fixtures-bundle -d symfony-demo-dir --no-progress
                    # composer dump-autoload --no-dev -d symfony-demo-dir

                    # 2. run an another project
                    rector-dir/vendor/bin/rector

                    cd drupal-dir
                    ls -lat ../../
                    ../rector-dir/vendor/bin/rector process web/core/modules/aggregator/src/Plugin/views/row/Rss.php --set deadcode --dry-run --config ../ci/config/rector-drupal.yaml
