name: Weekly Pull Requests

on:
    schedule:
        # https://crontab.guru/once-a-week
        -   cron: "0 0 * * 0"
        # todo make a bit human-like random: https://stackoverflow.com/a/9051029/1348344

jobs:
    weekly_pull_requests:
<<<<<<< HEAD
=======

        # dont run jobs on forks, because gh-tokens are not available
        if: github.event.pull_request.head.repo.full_name == github.repository

>>>>>>> fad995887... first run
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Re-Generate CHANGELOG.md"
                        run: "composer changelog"
                        branch: 'automated-regenerated-changelog'

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}

            # see https://github.com/shivammathur/setup-php
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: xdebug
                    tools: composer:v2

            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                run: composer install --no-progress --ansi

            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                run: ${{ matrix.actions.run }}

            # see https://github.com/peter-evans/create-pull-request
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    commit-message: "[automated] ${{ matrix.actions.name }}"
                    base: 'master'
                    branch: ${{ matrix.actions.branch }}
                    title: '[automated] ${{ matrix.actions.name }}'
                    delete-branch: true
                    author: "kaizen-ci <info@kaizen-ci.org>"
                    committer: "kaizen-ci <info@kaizen-ci.org>"
