services:
    Rector\CodeQuality\Rector\Assign\CombinedAssignRector: ~
    Rector\CodeQuality\Rector\BooleanAnd\SimplifyEmptyArrayCheckRector: ~
    Rector\CodeQuality\Rector\Foreach_\ForeachToInArrayRector: ~
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToCoalescingRector: ~
    Rector\CodeQuality\Rector\FuncCall\InArrayAndArrayKeysToArrayKeyExistsRector: ~
    Rector\CodeQuality\Rector\FuncCall\SimplifyFuncGetArgsCountRector: ~
    Rector\CodeQuality\Rector\FuncCall\SimplifyInArrayValuesRector: ~
    Rector\CodeQuality\Rector\FuncCall\SimplifyStrposLowerRector: ~
    Rector\CodeQuality\Rector\Identical\GetClassToInstanceOfRector: ~
    Rector\CodeQuality\Rector\Identical\SimplifyArraySearchRector: ~
    Rector\CodeQuality\Rector\Identical\SimplifyConditionsRector: ~
    Rector\CodeQuality\Rector\If_\SimplifyIfNotNullReturnRector: ~
    Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector: ~
    Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector: ~
    Rector\CodeQuality\Rector\Ternary\UnnecessaryTernaryExpressionRector: ~

    Rector\Php\Rector\FuncCall\RemoveExtraParametersRector: ~
    Rector\CodeQuality\Rector\BinaryOp\SimplifyDeMorganBinaryRector: ~
    Rector\CodeQuality\Rector\Ternary\SimplifyTautologyTernaryRector: ~
    Rector\CodeQuality\Rector\Foreach_\SimplifyForeachToArrayFilterRector: ~
    Rector\CodeQuality\Rector\FuncCall\SingleInArrayToCompareRector: ~
    Rector\CodeQuality\Rector\If_\SimplifyIfElseToTernaryRector: ~
    Rector\CodeQuality\Rector\Concat\JoinStringConcatRector: ~
    Rector\CodeQuality\Rector\If_\ConsecutiveNullCompareReturnsToNullCoalesceQueueRector: ~
    Rector\CodeQuality\Rector\If_\SimplifyIfIssetToNullCoalescingRector: ~
    Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector: ~
    Rector\CodeQuality\Rector\Equal\UseIdenticalOverEqualWithSameTypeRector: ~
    Rector\CodeQuality\Rector\Ternary\SimplifyDuplicatedTernaryRector: ~
    Rector\CodeQuality\Rector\Identical\SimplifyBoolIdenticalTrueRector: ~
